homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  time_zone: America/Bahia
  customize: !include misc/customize.yaml
  auth_providers:
   - type: homeassistant

mqtt:
  broker: !secret mqtt_ip_address
  username: !secret mqtt_username
  password: !secret mqtt_password

